
--ALTER session set NLS_DATE_FORMAT='DD/MM/YYYY';
SELECT CC.ID
    ,CC.NroCupo AS Alfanumerico
    ,TO_CHAR(CC.Fecha, 'DD/MM/YYYY') AS Fecha 
    ,CC.Centro AS CentroCupo
    ,CC.CentroDist
    ,CG.Grano AS CodGrano
    ,CG.Nombre AS NomGrano
    ,CASE
        WHEN CS.ESANULADO='N' AND CS.ESRECHAZADO='N' AND CS.CTG IS NULL AND
             (CS.FECHAACTIVADO IS NULL OR CS.FECHAACTIVADO = '1/1/0001') AND
             (CS.FECHAARRIBADO IS NULL OR CS.FECHAARRIBADO = '1/1/0001') AND
             (CS.FECHADESCARGADO IS NULL OR CS.FECHADESCARGADO = '1/1/0001') AND 
             (CS.FECHADESVIADOD IS NULL OR CS.FECHADESVIADOD = '1/1/0001') AND
             (CS.FECHADESVIADOO IS NULL OR CS.FECHADESVIADOO = '1/1/0001') THEN 0 /*'SIN CTG'*/
        WHEN CS.ESANULADO='N' AND CS.ESRECHAZADO='N' AND CS.CTG IS NOT NULL AND
             (CS.FECHAACTIVADO IS NOT NULL AND CS.FECHAACTIVADO <> '1/1/0001') AND
             (CS.FECHAARRIBADO IS NULL OR CS.FECHAARRIBADO = '1/1/0001') AND
             (CS.FECHADESCARGADO IS NULL OR CS.FECHADESCARGADO = '1/1/0001') AND 
             (CS.FECHADESVIADOD IS NULL OR CS.FECHADESVIADOD = '1/1/0001') AND
             (CS.FECHADESVIADOO IS NULL OR CS.FECHADESVIADOO = '1/1/0001') THEN 1 /*'ACTIVADO'*/
        WHEN CS.ESANULADO='N' AND CS.ESRECHAZADO='N' AND CS.CTG IS NOT NULL AND
             (CS.FECHAACTIVADO IS NOT NULL AND CS.FECHAACTIVADO <> '1/1/0001') AND
             (CS.FECHAARRIBADO IS NOT NULL AND CS.FECHAARRIBADO <> '1/1/0001') AND
             (CS.FECHADESCARGADO IS NULL OR CS.FECHADESCARGADO = '1/1/0001') AND 
             (CS.FECHADESVIADOD IS NULL OR CS.FECHADESVIADOD = '1/1/0001') AND
             (CS.FECHADESVIADOO IS NULL OR CS.FECHADESVIADOO = '1/1/0001') THEN 2 /*'ARRIBADO'*/
        WHEN CS.ESANULADO='N' AND CS.ESRECHAZADO='N' AND CS.CTG IS NOT NULL AND
             (CS.FECHAACTIVADO IS NOT NULL AND CS.FECHAACTIVADO <> '1/1/0001') AND
             (CS.FECHAARRIBADO IS NOT NULL AND CS.FECHAARRIBADO <> '1/1/0001') AND
             (CS.FECHADESCARGADO IS NOT NULL AND CS.FECHADESCARGADO <> '1/1/0001') AND 
             (CS.FECHADESVIADOD IS NULL OR CS.FECHADESVIADOD = '1/1/0001') AND
             (CS.FECHADESVIADOO IS NULL OR CS.FECHADESVIADOO = '1/1/0001') THEN 3 /*'DESCARGADO'*/
        WHEN CS.ESRECHAZADO = 'S' AND
             (CS.FECHARECHAZADO IS NOT NULL AND CS.FECHARECHAZADO <> '1/1/0001') AND
             (CS.CTG IS NOT NULL) AND 
             (CS.FECHAREACTIVADO IS NOT NULL AND CS.FECHAREACTIVADO <> '1/1/0001') THEN 3 /*'DESVIADO-REACTIVADO-DESCARGADO'*/ 
        WHEN (CS.FECHADESVIADOD IS NOT NULL AND CS.FECHADESVIADOD <> '1/1/0001') OR
             (CS.FECHADESVIADOO IS NOT NULL AND CS.FECHADESVIADOO <> '1/1/0001') THEN 4 /*'DESVIADO'*/
        WHEN CS.ESRECHAZADO = 'S' AND
             (CS.FECHARECHAZADO IS NOT NULL AND CS.FECHARECHAZADO <> '1/1/0001') AND
             (CS.CTG IS NULL) AND 
             (CS.FECHAREACTIVADO IS NULL OR CS.FECHAREACTIVADO = '1/1/0001') THEN 5 /*'RECHAZADO'*/
        WHEN CS.ESANULADO = 'S' AND
             (CS.FECHAANULADO IS NOT NULL AND CS.FECHAANULADO <> '1/1/0001') THEN 6 /*'ANULADO'*/
        ELSE -1
    END AS EstadoSTOP
    ,CS.CTG AS CTG
    --,TO_CHAR(CS.FECHACTG_DESDE, 'DD/MM/YYYY') AS CtgDesde
    --,TO_CHAR(CS.FECHACTG_HASTA, 'DD/MM/YYYY') AS CtgHasta
    ,LIMPIAR_CUIT(CP.Cuenta) AS CodDestino
    ,CP.NOMBRE AS NomDestino
    ,LIMPIAR_CUIT(TO_CHAR(CC.CUITDESTINATARIO)) AS CodDestinatario
    ,CC.NOMDESTINATARIO AS NomDestinatario
    --,LIMPIAR_CUIT(TO_CHAR(CC.CUITSOLICITANTE)) AS CodTitularDeCCPP
    --,CC.NOMSOLICITANTE AS NomTitularDeCCPP
    --,LIMPIAR_CUIT(TO_CHAR(CC.CUITRTECOMERCIALPROD)) AS CodRteComProductor
    --,CC.NOMRTECOMERCIALPROD AS NomRteComProductor
    ,LIMPIAR_CUIT(TO_CHAR(CC.CUITRTECOMERCIALVTAPRIM)) AS CodRteComVtaPrimaria
    ,CC.NOMRTECOMERCIALVTAPRIM AS NomRteComVtaPrimaria
    ,LIMPIAR_CUIT(TO_CHAR(CC.CUITINTERMEDIARIO)) AS CodRteComVtaSecundaria
    ,CC.NOMINTERMEDIARIO AS NomRteComVtaSecundaria
    ,LIMPIAR_CUIT(TO_CHAR(CC.CUITRTECOMERCIAL)) AS CodRteComVtaSecundaria2
    ,CC.NOMRTECOMERCIAL AS NomRteComVtaSecundaria2
    ,LIMPIAR_CUIT(TO_CHAR(CC.CUITMAT)) AS CodMercATermino
    ,CC.NOMMAT AS NomMercATermino
    ,LIMPIAR_CUIT(TO_CHAR(CC.CUITCORRVTA)) AS CodCorVtaPrimaria
    ,CC.NOMCORRVTA AS NomCorVtaPrimaria
    ,LIMPIAR_CUIT(TO_CHAR(CC.CUITCORRCOMP)) AS CodCorVtaSecundaria
    ,CC.NOMCORRCOMP AS NomCorVtaSecundaria
    --,LIMPIAR_CUIT(TO_CHAR(CC.CUITRTEENT)) AS CodEntregador
    --,CC.NOMRTEENT AS NomEntregador
    ,LIMPIAR_CUIT(TO_CHAR(CC.VENDCTA)) AS CodVendSIL
    ,CVEND.NOMBRE AS NomVendSIL
    ,CASE 
        WHEN CC.VENDCYO = CC.COMPCTA THEN LIMPIAR_CUIT(TO_CHAR(NVL(CCP.COMPCTA, ''))) 
        ELSE LIMPIAR_CUIT(TO_CHAR(NVL(CC.COMPCTA, ''))) 
    END AS CodCompSIL
    ,CASE 
        WHEN CC.VENDCYO = CC.COMPCTA THEN CCPCOMP.NOMBRE 
        ELSE CCCOMP.NOMBRE 
    END AS NomCompSIL  
    --,LIMPIAR_CUIT(TO_CHAR(CS.IDCUITINTERFLETE)) AS CodFlete
    --,CODFLETE.NOMBRE AS NomFlete
    --,LIMPIAR_CUIT(TO_CHAR(CS.IDCUITTRANSPORTISTA)) AS CodTransportista
    --,CODTRANSPORTISTA.NOMBRE AS NomTransportista
    --,LIMPIAR_CUIT(TO_CHAR(CS.IDCUITCHOFER)) AS CodChofer
    --,CODCHOFER.NOMBRE AS NomChofer
    --,TO_CHAR(CS.CARTAPORTE) AS CartaPorte
    --,TO_CHAR(CS.FECHACP_VTO, 'DD/MM/YYYY') AS CartaPorteVto
    --,TO_CHAR(CS.FECHACP_CARGA, 'DD/MM/YYYY') AS CartaPorteFechaCarga
    ,1 AS EstaSIL
    ,CC.STATUS AS EstadoSIL
    ,TO_CHAR(CC.FECHAYHORAINFORMADO, 'DD/MM/YYYY') AS FechaInformadoSIL
    ,CASE WHEN CS.IDCUPO IS NULL THEN 0 ELSE 1 END AS EstaSTOP  
    --,TO_CHAR(CS.CUITCHOFERAFIP) AS CuitChoferAfip
    --,CS.CUITCORREDORCAFIP AS CuitCorredorCAfip
    --,CS.CUITCORREDORVAFIP AS CuitCorredorVAfip
    --,CS.CUITDESTINATARIOAFIP AS CuitDestinatarioAfip
    --,CS.CUITDESTINOAFIP AS CuitDestinoAfip
    --,CS.CUITINTERAFIP AS CuitInterAfip
    --,CS.CUITINTERFLETEAFIP AS CuitInterFleteAfip
    --,CS.CUITMATERMINOAFIP AS CuitMaterminoAfip
    --,CS.CUITORIGENAFIP AS CuitOrigenAfip
    --,CS.CUITREMCOMERCIALAFIP AS CuitRemComercialAfip
    --,CS.CUITENTREGADORAFIP AS CuitEntregadorAfip
    --,CS.CUITTRANSPORTISTAAFIP AS CuitTransportistaAfip
    ,TO_CHAR(CS.ESTADO) AS Estado
    ,CS.ESANULADO AS EsAnulado
    ,CS.ESRECHAZADO AS EsRechazado
    ,CS.DESVIO AS Desvio
    ,CS.IDCUPO AS IdCupoStop
    ,CS.IDTURNODETALLE AS IdTurnoDetalle
    ,CS.IDCUPOESTADO As IdCupoEstadoStop
    --,TO_CHAR(CS.FECHAACTIVADO, 'DD/MM/YYYY') AS FechaActivado
    --,TO_CHAR(CS.FECHAARRIBADO, 'DD/MM/YYYY') AS FechaArribado
    --,TO_CHAR(CS.FECHARECHAZADO, 'DD/MM/YYYY') AS FechaRechazado
    --,TO_CHAR(CS.FECHADESVIADOO, 'DD/MM/YYYY') AS FechaDesviadoO
    --,TO_CHAR(CS.FECHADESVIADOD, 'DD/MM/YYYY') AS FechaDesviadoD
    --,TO_CHAR(CS.FECHAREGRESADO, 'DD/MM/YYYY') AS FechaRegresado
    --,TO_CHAR(CS.FECHAANULADO, 'DD/MM/YYYY') AS FechaAnulado
    --,TO_CHAR(CS.FECHACONFIRMADO, 'DD/MM/YYYY') AS FechaConfirmado
    --,TO_CHAR(CS.FECHADESCARGADO, 'DD/MM/YYYY') AS FechaDescargado
    --,TO_CHAR(CS.FECHAREACTIVADO, 'DD/MM/YYYY') AS FechaReactivado
    --,TO_CHAR(CS.FECHATOMADO, 'DD/MM/YYYY') AS FechaTomado
    --,TO_CHAR(CS.CREADO, 'DD/MM/YYYY') AS FechaCreado
    --,TO_CHAR(CS.MODIFICADO, 'DD/MM/YYYY') AS FechaModificado
    ,CS.CREADOPOR AS CreadoPor
    ,CS.MODIFICADOPOR AS ModificadoPor
    --,CS.CODLOCALIDADORIGEN AS CodLocalidadOrigen
    --,CS.CODLOCALIDADDESTINO AS CodLocalidadDestino
    ,TO_CHAR(CS.COSECHA) AS Cosecha
    ,TO_CHAR(CS.RENSPA) AS Renspa
    --,CS.NROESTABORIGEN AS NroEstabOrigen
    --,CS.PESOORIGINAL AS PesoOriginal
    --,CS.PESONETOESTIMADO AS PesoNetoEstimado
    --,CS.KMRECORRER AS KmRecorrer
    --,CS.VALIDAKM AS ValidaKm
    --,CS.CANTHSSALIDACAMION AS CantHsSalidaCamion
    --,TO_CHAR(CS.DOMINIO) AS Dominio
    --,TO_CHAR(CS.DOMINIO_1) AS Dominio1
    --,TO_CHAR(CS.DOMINIO_2) AS Dominio2
    ,TO_CHAR(CS.NROCONTRATO) AS NroContrato
    ,CS.NROPLANTARUCA AS NroPlantaRuca
    ,CS.IDESTADOENPLANTA AS IdEstadoEnPlanta
    --,CS.CONSULTADOXAFIP AS ConsultadoPorAfip
    --,TO_CHAR(CS.ULTIMA_LATITUD) AS UltimaLatitud
    --,TO_CHAR(CS.ULTIMA_LONGITUD) AS UltimaLongitud
    ,CC.MOTBAJA AS MotivoBajaSil
    ,CC.OBSERVA AS ObservacionSil
    ,CC.USUARIO AS UsuarioSil
    ,CASE 
        WHEN RPS.NroPuertoSIL IS NOT NULL THEN 1
        ELSE 0
    END AS Turneable
FROM CuposCorre CC
LEFT OUTER JOIN CuposCorre CCP 
    ON CCP.TIPO = 1 
    AND CCP.VENDCYO = CC.COMPCTA 
    AND CCP.NROCUPO = CC.NROCUPO 
    AND CCP.IDORIGEN = CC.IDORIGEN 
    AND CCP.FECHA = CC.FECHA 
    AND CCP.ID <> CC.ID 
INNER JOIN MVCuposGrano CG ON CC.Grano = CG.Grano
INNER JOIN MVCuposPuerto CP ON CC.PuertoCta = CP.Cuenta
LEFT OUTER JOIN MVCuposVendedor CVend ON CC.VENDCTA = CVEND.CUENTA
LEFT OUTER JOIN CuposStop CS ON CC.NroCupo = CS.idcupoterminal AND CC.FECHA = CS.FECHA
LEFT OUTER JOIN CUPOSCUITMV CodFlete ON CODFLETE.CUENTA = CS.IDCUITINTERFLETE
LEFT OUTER JOIN CUPOSCUITMV CodTransportista ON CODTRANSPORTISTA.CUENTA = CS.IDCUITTRANSPORTISTA
LEFT OUTER JOIN CUPOSCUITMV CodChofer ON CODCHOFER.CUENTA = CS.IDCUITCHOFER
-- JOIN adicionales para evitar subqueries en SELECT
LEFT OUTER JOIN MVCuposComprador CCCOMP ON CCCOMP.cuenta = CC.COMPCTA
LEFT OUTER JOIN MVCuposComprador CCPCOMP ON CCPCOMP.cuenta = CCP.COMPCTA
LEFT JOIN RelacionPuertoSilPuertoStop RPS ON RPS.NroPuertoSIL = CC.PuertoCta
  AND ( :compradores IS NULL OR EXISTS (
        SELECT 1 FROM TABLE(split_string(:compradores)) t WHERE t.COLUMN_VALUE = CC.COMPCTA
      ))
  AND ( :vendedores IS NULL OR EXISTS (
        SELECT 1 FROM TABLE(split_string(:vendedores)) t WHERE t.COLUMN_VALUE = CC.VENDCTA
      ))
  AND ( :productos IS NULL OR EXISTS (
        SELECT 1 FROM TABLE(split_string(:productos)) t WHERE t.COLUMN_VALUE = CC.Grano
      ))
  AND ( :destinos IS NULL OR EXISTS (
        SELECT 1 FROM TABLE(split_string(:destinos)) t WHERE t.COLUMN_VALUE = CP.Cuenta
      ))
  AND ( :centros IS NULL OR EXISTS (
        SELECT 1 FROM TABLE(split_string(:centros)) t WHERE t.COLUMN_VALUE = CC.Centro
      ))
  AND CC.TIPO = 1
  AND CC.VENDCTA <> CC.VENDCYO
  AND CC.STATUS = 4
