INSERT INTO [dbo].[Cupo]
	([Alfanumerico]
	,[Fecha]
	,[CentroCupo]
	,[CentroDist]
	,[CodGrano]
	,[NomGrano]
	,[EstadoSTOP]
	,[CTG]
	,[CodDestino]
	,[NomDestino]
	,[CodDestinatario]
	,[NomDestinatario]
	,[CodTitularDeCCPP]
	,[NomTitularDeCCPP]
	,[NomRteComProductor]
	,[CodRteComProductor]
	,[CodRteComVtaPrimaria]
	,[NomRteComVtaPrimaria]
	,[CodRteComVtaSecundaria]
	,[NomRteComVtaSecundaria]
	,[CodRteComVtaSecundaria2]
	,[NomRteComVtaSecundaria2]
	,[CodMercATermino]
	,[NomMercATermino]
	,[CodCorVtaPrimaria]
	,[NomCorVtaPrimaria]
	,[CodCorVtaSecundaria]
	,[NomCorVtaSecundaria]
	,[UsuarioSIL]
	,[EstaSIL]
	,[EstadoSIL]
	,[FechaInformadoSIL]
	,[CTGDesde]
	,[CTGHasta]
	,[CantHsSalidaCamion]
	,[CartaPorte]
	,[CartaPorteFechaCarga]
	,[CartaPorteVto]
	,[CodChofer]
	,[CodEntregador]
	,[CodFlete]
	,[CodLocalidadDestino]
	,[CodLocalidadOrigen]
	,[CodTransportista]
	,[CodVendSIL]
	,[ConsultadoPorAfip]
	,[Cosecha]
	,[CreadoPor]
	,[CuitChoferAfip]
	,[CuitCorredorCAfip]
	,[CuitCorredorVAfip]
	,[CuitDestinatarioAfip]
	,[CuitDestinoAfip]
	,[CuitEntregadorAfip]
	,[CuitInterAfip]
	,[CuitInterFleteAfip]
	,[CuitMaterminoAfip]
	,[CuitOrigenAfip]
	,[CuitRemComercialAfip]
	,[CuitTransportistaAfip]
	,[Desvio]
	,[Dominio]
	,[Dominio1]
	,[Dominio2]
	,[EsAnulado]
	,[EsRechazado]
	,[EstaSTOP]
	,[Estado]
	,[FechaActivado]
	,[FechaAnulado]
	,[FechaArribado]
	,[FechaConfirmado]
	,[FechaCreado]
	,[FechaDescargado]
	,[FechaDesviadoD]
	,[FechaDesviadoO]
	,[FechaModificado]
	,[FechaReactivado]
	,[FechaRechazado]
	,[FechaRegresado]
	,[FechaTomado]
	,[IdCupoEstadoStop]
	,[IdCupoStop]
	,[IdEstadoEnPlanta]
	,[IdTurnoDetalle]
	,[KMRecorrer]
	,[ModificadoPor]
	,[MotivoBajaSIL]
	,[NomChofer]
	,[NomEntregador]
	,[NomFlete]
	,[NomTransportista]
	,[NomVendSIL]
	,[NroContrato]
	,[NroEstabOrigen]
	,[NroPlantaRUCA]
	,[ObservacionSIL]
	,[PesoNetoEstimado]
	,[PesoOriginal]
	,[RENSPA]
	,[UltimaLatitud]
	,[UltimaLongitud]
	,[ValidaKM]
	,[CodCompSIL]
	,[NomCompSIL]
	,[SyncDate])
VALUES
	(@paramAlfanumerico,
	@paramFecha,
	@paramCentroCupo,
	@paramCentroDist,
	@paramCodGrano,
	@paramNomGrano,
	@paramEstadoSTOP,
	@paramCTG,
	@paramCodDestino,
	@paramNomDestino,
	@paramCodDestinatario,
	@paramNomDestinatario,
	@paramCodTitularDeCCPP,
	@paramNomTitularDeCCPP,
	@paramNomRteComProductor,
	@paramCodRteComProductor,
	@paramCodRteComVtaPrimaria,
	@paramNomRteComVtaPrimaria,
	@paramCodRteComVtaSecundaria,
	@paramNomRteComVtaSecundaria,
	@paramCodRteComVtaSecundaria2,
	@paramNomRteComVtaSecundaria2,
	@paramCodMercATermino,
	@paramNomMercATermino,
	@paramCodCorVtaPrimaria,
	@paramNomCorVtaPrimaria,
	@paramCodCorVtaSecundaria,
	@paramNomCorVtaSecundaria,
	@paramUsuarioSIL,
	@paramEstaSIL,
	@paramEstadoSIL,
	@paramFechaInformadoSIL,
	@paramCTGDesde,
	@paramCTGHasta,
	@paramCantHsSalidaCamion,
	@paramCartaPorte,
	@paramCartaPorteFechaCarga,
	@paramCartaPorteVto,
	@paramCodChofer,
	@paramCodEntregador,
	@paramCodFlete,
	@paramCodLocalidadDestino,
	@paramCodLocalidadOrigen,
	@paramCodTransportista,
	@paramCodVendSIL,
	@paramConsultadoPorAfip,
	@paramCosecha,
	@paramCreadoPor,
	@paramCuitChoferAfip,
	@paramCuitCorredorCAfip,
	@paramCuitCorredorVAfip,
	@paramCuitDestinatarioAfip,
	@paramCuitDestinoAfip,
	@paramCuitEntregadorAfip,
	@paramCuitInterAfip,
	@paramCuitInterFleteAfip,
	@paramCuitMaterminoAfip,
	@paramCuitOrigenAfip,
	@paramCuitRemComercialAfip,
	@paramCuitTransportistaAfip,
	@paramDesvio,
	@paramDominio,
	@paramDominio1,
	@paramDominio2,
	@paramEsAnulado,
	@paramEsRechazado,
	@paramEstaSTOP,
	@paramEstado,
	@paramFechaActivado,
	@paramFechaAnulado,
	@paramFechaArribado,
	@paramFechaConfirmado,
	@paramFechaCreado,
	@paramFechaDescargado,
	@paramFechaDesviadoD,
	@paramFechaDesviadoO,
	@paramFechaModificado,
	@paramFechaReactivado,
	@paramFechaRechazado,
	@paramFechaRegresado,
	@paramFechaTomado,
	@paramIdCupoEstadoStop,
	@paramIdCupoStop,
	@paramIdEstadoEnPlanta,
	@paramIdTurnoDetalle,
	@paramKMRecorrer,
	@paramModificadoPor,
	@paramMotivoBajaSIL,
	@paramNomChofer,
	@paramNomEntregador,
	@paramNomFlete,
	@paramNomTransportista,
	@paramNomVendSIL,
	@paramNroContrato,
	@paramNroEstabOrigen,
	@paramNroPlantaRUCA,
	@paramObservacionSIL,
	@paramPesoNetoEstimado,
	@paramPesoOriginal,
	@paramRENSPA,
	@paramUltimaLatitud,
	@paramUltimaLongitud,
	@paramValidaKM,
	@paramCodCompSIL,
	@paramNomCompSIL,
	@paramSyncDate
)