// <auto-generated />
using System;
using Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(SQLDBContext))]
    [Migration("20220824222752_NewColumnInCupoTable")]
    partial class NewColumnInCupoTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.Externo.Cupo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Alfanumerico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CTG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CTGDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CTGHasta")
                        .HasColumnType("datetime2");

                    b.Property<int>("CantHsSalidaCamion")
                        .HasColumnType("int");

                    b.Property<string>("CartaPorte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CartaPorteFechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CartaPorteVto")
                        .HasColumnType("datetime2");

                    b.Property<string>("CentroCupo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CentroDist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodChofer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodCorVtaPrimaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodCorVtaSecundaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodDestinatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodEntregador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodFlete")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodGrano")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodLocalidadDestino")
                        .HasColumnType("int");

                    b.Property<int>("CodLocalidadOrigen")
                        .HasColumnType("int");

                    b.Property<string>("CodMercATermino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodRteComProductor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodRteComVtaPrimaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodRteComVtaSecundaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodRteComVtaSecundaria2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodTitularDeCCPP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodTransportista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodVendSIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ConsultadoPorAfip")
                        .HasColumnType("bit");

                    b.Property<string>("Cosecha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreadoPor")
                        .HasColumnType("int");

                    b.Property<bool>("CuitChoferAfip")
                        .HasColumnType("bit");

                    b.Property<bool>("CuitCorredorCAfip")
                        .HasColumnType("bit");

                    b.Property<bool>("CuitCorredorVAfip")
                        .HasColumnType("bit");

                    b.Property<bool>("CuitDestinatarioAfip")
                        .HasColumnType("bit");

                    b.Property<bool>("CuitDestinoAfip")
                        .HasColumnType("bit");

                    b.Property<bool>("CuitEntregadorAfip")
                        .HasColumnType("bit");

                    b.Property<bool>("CuitInterAfip")
                        .HasColumnType("bit");

                    b.Property<bool>("CuitInterFleteAfip")
                        .HasColumnType("bit");

                    b.Property<bool>("CuitMaterminoAfip")
                        .HasColumnType("bit");

                    b.Property<bool>("CuitOrigenAfip")
                        .HasColumnType("bit");

                    b.Property<bool>("CuitRemComercialAfip")
                        .HasColumnType("bit");

                    b.Property<bool>("CuitTransportistaAfip")
                        .HasColumnType("bit");

                    b.Property<bool>("Desvio")
                        .HasColumnType("bit");

                    b.Property<string>("Dominio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dominio1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dominio2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsAnulado")
                        .HasColumnType("bit");

                    b.Property<bool>("EsRechazado")
                        .HasColumnType("bit");

                    b.Property<bool>("EstaSIL")
                        .HasColumnType("bit");

                    b.Property<bool>("EstaSTOP")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("EstadoSIL")
                        .HasColumnType("smallint");

                    b.Property<string>("EstadoSTOP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaActivado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaAnulado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaArribado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaConfirmado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDescargado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDesviadoD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDesviadoO")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInformadoSIL")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReactivado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRechazado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegresado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaTomado")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdCupoEstadoStop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdCupoStop")
                        .HasColumnType("bigint");

                    b.Property<short>("IdEstadoEnPlanta")
                        .HasColumnType("smallint");

                    b.Property<string>("IdTurnoDetalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("KMRecorrer")
                        .HasColumnType("float");

                    b.Property<int>("ModificadoPor")
                        .HasColumnType("int");

                    b.Property<string>("MotivoBajaSIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomChofer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCorVtaPrimaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCorVtaSecundaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomDestinatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomEntregador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomFlete")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomGrano")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomMercATermino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomRteComProductor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomRteComVtaPrimaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomRteComVtaSecundaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomRteComVtaSecundaria2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomTitularDeCCPP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomTransportista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomVendSIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroContrato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NroEstabOrigen")
                        .HasColumnType("int");

                    b.Property<int>("NroPlantaRUCA")
                        .HasColumnType("int");

                    b.Property<string>("ObservacionSIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PesoNetoEstimado")
                        .HasColumnType("int");

                    b.Property<int>("PesoOriginal")
                        .HasColumnType("int");

                    b.Property<string>("RENSPA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UltimaLatitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UltimaLongitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioSIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ValidaKM")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Cupo");
                });

            modelBuilder.Entity("Domain.Entities.ListasContactos.Contacto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TipoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.HasIndex("TipoId");

                    b.ToTable("Contacto");
                });

            modelBuilder.Entity("Domain.Entities.ListasContactos.ListaContactos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ListaContactos");
                });

            modelBuilder.Entity("Domain.Entities.ListasContactos.TipoContacto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoContacto");
                });

            modelBuilder.Entity("Domain.Entities.Personas.Centro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Centro");
                });

            modelBuilder.Entity("Domain.Entities.Personas.Cuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CupoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroCuenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CupoId");

                    b.ToTable("Cuenta");
                });

            modelBuilder.Entity("Domain.Entities.Personas.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CentroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CuentaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ZonaComercialId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("CuentaId");

                    b.HasIndex("RolId");

                    b.HasIndex("ZonaComercialId");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("Domain.Entities.Personas.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("Domain.Entities.Personas.ZonaComercial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ZonaComercial");
                });

            modelBuilder.Entity("Domain.Entities.Reportes.InstanciaReporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReporteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReporteId");

                    b.ToTable("InstanciaReporte");
                });

            modelBuilder.Entity("Domain.Entities.Reportes.Parametro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InstanciaReporteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Parametros")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstanciaReporteId");

                    b.ToTable("Parametro");
                });

            modelBuilder.Entity("Domain.Entities.Reportes.Reporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reporte");
                });

            modelBuilder.Entity("ListaContactosListaContactos", b =>
                {
                    b.Property<Guid>("ListasHijasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ListasPadresId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ListasHijasId", "ListasPadresId");

                    b.HasIndex("ListasPadresId");

                    b.ToTable("ListaContactosListaContactos");
                });

            modelBuilder.Entity("ListaContactosPersona", b =>
                {
                    b.Property<Guid>("ListasPadreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonasId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ListasPadreId", "PersonasId");

                    b.HasIndex("PersonasId");

                    b.ToTable("ListaContactosPersona");
                });

            modelBuilder.Entity("Domain.Entities.ListasContactos.Contacto", b =>
                {
                    b.HasOne("Domain.Entities.Personas.Persona", "Persona")
                        .WithMany("Contactos")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ListasContactos.TipoContacto", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Domain.Entities.Personas.Cuenta", b =>
                {
                    b.HasOne("Domain.Entities.Externo.Cupo", "Cupo")
                        .WithMany()
                        .HasForeignKey("CupoId");

                    b.Navigation("Cupo");
                });

            modelBuilder.Entity("Domain.Entities.Personas.Persona", b =>
                {
                    b.HasOne("Domain.Entities.Personas.Centro", "Centro")
                        .WithMany()
                        .HasForeignKey("CentroId");

                    b.HasOne("Domain.Entities.Personas.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("CuentaId");

                    b.HasOne("Domain.Entities.Personas.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId");

                    b.HasOne("Domain.Entities.Personas.ZonaComercial", "ZonaComercial")
                        .WithMany()
                        .HasForeignKey("ZonaComercialId");

                    b.Navigation("Centro");

                    b.Navigation("Cuenta");

                    b.Navigation("Rol");

                    b.Navigation("ZonaComercial");
                });

            modelBuilder.Entity("Domain.Entities.Reportes.InstanciaReporte", b =>
                {
                    b.HasOne("Domain.Entities.Reportes.Reporte", "Reporte")
                        .WithMany()
                        .HasForeignKey("ReporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("Domain.Entities.Reportes.Parametro", b =>
                {
                    b.HasOne("Domain.Entities.Reportes.InstanciaReporte", null)
                        .WithMany("Parametros")
                        .HasForeignKey("InstanciaReporteId");
                });

            modelBuilder.Entity("ListaContactosListaContactos", b =>
                {
                    b.HasOne("Domain.Entities.ListasContactos.ListaContactos", null)
                        .WithMany()
                        .HasForeignKey("ListasHijasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ListasContactos.ListaContactos", null)
                        .WithMany()
                        .HasForeignKey("ListasPadresId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ListaContactosPersona", b =>
                {
                    b.HasOne("Domain.Entities.ListasContactos.ListaContactos", null)
                        .WithMany()
                        .HasForeignKey("ListasPadreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Personas.Persona", null)
                        .WithMany()
                        .HasForeignKey("PersonasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Personas.Persona", b =>
                {
                    b.Navigation("Contactos");
                });

            modelBuilder.Entity("Domain.Entities.Reportes.InstanciaReporte", b =>
                {
                    b.Navigation("Parametros");
                });
#pragma warning restore 612, 618
        }
    }
}
